export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_PRODUCTS_MEN: "SET_PRODUCTS_MEN",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  ADD_FAVORITE: "ADD_FAVORITE",
  REMOVE_FAVORITE: "REMOVE_FAVORITE",
  ADD_CART: "ADD_CART",
  REMOVE_CART: "REMOVE_CART",
  ADD_CART_QUANTITY: "ADD_CART_QUANTITY",
  REMOVE_CART_QUANTITY: "REMOVE_CART_QUANTITY",
};
